[phases.setup]
nixPkgs = ["php82", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.tokenizer", "php82Extensions.fileinfo", "composer", "caddy", "php82Packages.php-fpm"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "bash /app/start.sh"